services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: juba
      POSTGRES_PASSWORD: shuher123
      POSTGRES_DB: base
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U juba -d base"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 -- 
      gunicorn --bind 0.0.0.0:8000 
      --workers 4 
      --timeout 120 
      --access-logfile - 
      --error-logfile - 
      corn.wsgi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://juba:shuher123@db:5432/base
      - DJANGO_SETTINGS_MODULE=corn.settings
      - PYTHONUNBUFFERED=1
    restart: unless-stopped  # Автоматический перезапуск при падении

volumes:
  postgres_data: